### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by urbanoVIII** [geochicasosm/data_scripts_lascallesdelasmujeres#1]
Hola : )
no puedo instalar los paquetes npm, me da este error:
"Unexpected token / in JSON at position 422 while parsing near '...ad={2} --wikipedia",//npm run step123 [-...'"

 adjunto el log.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose npm-session 2921e7d40dfd1ae1
5 silly install runPreinstallTopLevelLifecycles
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose stack Error: Failed to parse json
8 verbose stack Unexpected token / in JSON at position 422 while parsing near '...ad={2} --wikipedia",//npm run step123 [-...'
8 verbose stack     at parseError (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:11)
8 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:104:26)
8 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:5
8 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
8 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)
9 verbose cwd /home/marco/Programming/data_scripts_lascallesdelasmujeres
10 verbose Linux 4.13.0-39-generic
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
12 verbose node v9.11.1
13 verbose npm  v5.6.0
14 error file /home/marco/Programming/data_scripts_lascallesdelasmujeres/package.json
15 error code EJSONPARSE
16 error Failed to parse json
16 error Unexpected token / in JSON at position 422 while parsing near '...ad={2} --wikipedia",//npm run step123 [-...'
17 error File: /home/marco/Programming/data_scripts_lascallesdelasmujeres/package.json
18 error Failed to parse package.json data.
18 error package.json must be actual JSON, not just JavaScript.
18 error
18 error Tell the package author to fix their package.json file. JSON.parse
19 verbose exit [ 1, true ]

**Comment by jessisena** [comment]
Fixed in May 2, 2018 commit
