### ISSUE TITLE
npm install error al intentar descargar sqlite3@3.1.13

### ISSUE THREAD

**Issue by kuratowsky** [geochicasosm/data_scripts_lascallesdelasmujeres#13]
Al realizar el `npm install` se produce un error al intentar descargar sqlite3@3.1.13

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp)
```
AL acceder directamente a la url muestra "Acces Denied"

![image](https://user-images.githubusercontent.com/482854/80352400-21085700-8874-11ea-9b17-b13e337ef89e.png)

¿Cómo lo podemos corregir?

**Comment by kuratowsky** [comment]
Remito el log debug de NPM
[2020-04-27T08_42_47_960Z-debug.log](https://github.com/geochicasosm/data_scripts_lascallesdelasmujeres/files/4538454/2020-04-27T08_42_47_960Z-debug.log)

**Comment by geochicasosm** [comment]
Hola,

es necesario usar una versión de node <10 (tal como se indica en las [instrucciones](https://github.com/geochicasosm/data_scripts_lascallesdelasmujeres#instalaci%C3%B3n-y-preparaci%C3%B3n-de-entorno)) y parece que estás usando la 10.16.3.

Esto debería solucionar el problema 👍

**Comment by jessisena** [comment]
Hola,

es necesario usar una versión de node <10 (tal como se indica en las [instrucciones](https://github.com/geochicasosm/data_scripts_lascallesdelasmujeres#instalaci%C3%B3n-y-preparaci%C3%B3n-de-entorno)) y parece que estás usando la 10.16.3.

Esto debería solucionar el problema 👍

**Comment by kuratowsky** [comment]
Hola @jessisena,
Toda la razón, en las instrucciones indica que debe ser una versión de node <10.
He realizado la prueba dentro de un contenedor docker.

- He instalado la versión que recomendáis
![image](https://user-images.githubusercontent.com/482854/80868312-0aaa3300-8c9a-11ea-8cd0-9c8061d2252c.png)
- He clonado el proyecto 
- He ejecutado el npm install y ... error al intentar instalar sqlite3.
![image](https://user-images.githubusercontent.com/482854/80868351-53fa8280-8c9a-11ea-9048-dfd72c778caa.png)

Por si a alguien le pasa lo mismo, lo he arreglado aplicando la siguiente configuración 
https://github.com/jansmolders86/mediacenterjs/issues/191#issuecomment-317437604

Saludos y gracias!
